### PR TITLE
HONEYPOTS

### PR DESCRIPTION
**Pull request by megha070**
NOTE:
- Please fill out the template below 

## Did you read the instructions in the [README](https://github.com/the-ethan-hunt/first-timers-guide/blob/master/README.md)?
Y
> Y/N

## Have you read the instructions in [CONTRIBUTING](https://github.com/the-ethan-hunt/first-timers-guide/blob/master/CONTRIBUTING.md)?
Y
> Y/N

## Have you written this article by yourself? Have you taken inspiration from anywhere and then written it in your words?
YES I TOOK INSPIRATION FROM VARIOUS SOURCES WHICH INCLUDES QUORA,WIKIPEDIA AND YOUTUBE.
> [Write here. Be specific.]

### CODE REVIEW

**Comment by the-ethan-hunt** [comment]
@megha070 , your file is a `.txt` file. It needs to be a Markdown file.  For writing in Markdown please refer this [cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)

**Comment by megha070** [comment]
okay @the-ethan-hunt .
Thanks a lot.

**Comment by the-ethan-hunt** [comment]
Good going @megha070 . Please take care of the minor typos next time.

**Comment by megha070** [comment]
Thanks a lot!!

**Pull request merged**
