### PR TITLE
[Improvement] Created/Added a Website #64

### PR DESCRIPTION
**Pull request by EdgeKing810**
## Did you read the instructions in the [README](https://github.com/the-ethan-hunt/first-timers-guide/blob/master/README.md)?

> Y

## Have you read the instructions in [CONTRIBUTING](https://github.com/the-ethan-hunt/first-timers-guide/blob/master/CONTRIBUTING.md)?

> Y

## Have you written this article by yourself? Have you taken inspiration from anywhere and then written it in your words?

> I have not taken up any articles. Just copied and converted the ``README.md`` into the ``index`` page for the website.

This is a page for https://github.com/the-ethan-hunt/first-timers-guide/issues/64. If this is approved, I'll work on https://github.com/the-ethan-hunt/first-timers-guide/issues/216 too.

### CODE REVIEW

**Comment by EdgeKing810** [comment]
Also, please let me know of any possible improvements or what I must do more.

**Comment by EdgeKing810** [comment]
nvm, I'm taking and fixing #216 along

**Comment by EdgeKing810** [comment]
> Also, please let me know of any possible improvements or what I must do more.

again that for issue #216 too...

**Comment by the-ethan-hunt** [comment]
Issue #216  is taken care of; Is this PR WIP for Issue #64 ?
@EdgeKing810 would it be great to host this website on Jekyll? 
An ideal website for this project: The homepage should feature a search bar whereupon typing the first letter, a list of options come up; similar to Google Search. Would like to hear your opinion on this.

**Comment by EdgeKing810** [comment]
[Latest Comment bases on the latest commits]

I've replaced ``index.rst`` with ``index.html``. Note that I have not added any CSS yet. I'll need some answers for my comment before this one and if you want any CSS styling done, lemme know in which elements and stuff you'd want it @the-ethan-hunt.

As far as the search option is concerned, I need to make sure that I understood it correctly and whether it should return links of ``.md`` files of that repo based on the search keywords.

**Comment by the-ethan-hunt** [comment]
@EdgeKing810 : This PR has solved Issue #216 .
Your search idea is correct, indeed. That's what we need to do: the search function will return links of `.md` files of this repo as per the user's search.
Regarding the CSS part, you are free to work upon it as you like; I don't recommend or support any particular styling, it depends on the contributor. :smile:

**Comment by EdgeKing810** [comment]
Okay then, I'll work on that search function and try to add some CSS. :smiley:

**Comment by EdgeKing810** [comment]
Hey @the-ethan-hunt! Managed to do the search thing you asked me! :tada: 

I also got to learn some JavaScript and I honestly love it! In that latest update, I also made some minor improvements in the docs so that they appear a bit better. And for the CSS part, I have not done much things but I put classes with some of the elements, so... tweak them according to your preference if you want!

I hope you like the work I did! If you need other improvements to be done or if you are not satisfied, please let me know!

**Comment by the-ethan-hunt** [comment]
@EdgeKing810 , excellent work indeed! :tada: 
Let's launch it!

**Comment by EdgeKing810** [comment]
Yayy :smile:

**Pull request merged**
