### PR TITLE
Add Anti-Patterns Non Issue NPearson

### PR DESCRIPTION
**Pull request by NathanPearson**
## Did you read the instructions in the [README](https://github.com/the-ethan-hunt/first-timers-guide/blob/master/README.md)?

> Y

## Have you read the instructions in [CONTRIBUTING](https://github.com/the-ethan-hunt/first-timers-guide/blob/master/CONTRIBUTING.md)?

> Y

## Have you written this article by yourself? Have you taken inspiration from anywhere and then written it in your words?

> Yes the article was written by myself. I did take inspiration from multiple references and then wrote the article in my own words.
References:
http://wiki.c2.com/?AntiPattern
http://wiki.c2.com/?AntiPatternsCatalog
https://sourcemaking.com/antipatterns/software-development-antipatterns
https://sahandsaba.com/nine-anti-patterns-every-programmer-should-be-aware-of-with-examples.html

### CODE REVIEW

**Comment by the-ethan-hunt** [comment]
Nice article @NathanPearson . A few things, however:
- Put the article in `UX_design`
- Please carry out proper formatting of the document. I am not able to check if it is plagiarised or not. Perhaps this [cheatsheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet) might help.

**Comment by NathanPearson** [comment]
Sure thing. I assumed a folder may be appropriate as others could elaborate on individual antipatterns. I'll fix the formatting issue as well.

**Comment by NathanPearson** [comment]
File moved and the formatting should now be acceptable. If there are any other issues please let me know.

**Comment by the-ethan-hunt** [comment]
Merging this.

**Pull request merged**
