### PR TITLE
Salma is adding an article - First timers guide to Vue Material

### PR DESCRIPTION
**Pull request by Sultaness**
NOTE:
- Please fill out the template below 

## Did you read the instructions in the [README](https://github.com/the-ethan-hunt/first-timers-guide/blob/master/README.md)?

> Y

## Have you read the instructions in [CONTRIBUTING](https://github.com/the-ethan-hunt/first-timers-guide/blob/master/CONTRIBUTING.md)?

> Y

## Have you written this article by yourself? Have you taken inspiration from anywhere and then written it in your words?

> I referred https://vuematerial.io/getting-started to learn Vue Material by myself and I am writing this article after creating two Vue Material Projects.

### CODE REVIEW

**Comment by the-ethan-hunt** [comment]
Well writen @Sultaness ! Can you also state why Vue.js is more preferred than other frameworks( perhaps from personal experience)?

**Comment by RN0311** [comment]
@the-ethan-hunt : I guess, sufficient knowledge is added by @Sultaness! Indeed, her work is good! Lets' merged it if possible! ;)

**Comment by Sultaness** [comment]
@the-ethan-hunt I have made some changes and also added Vue JS preference over other frameworks. Please review and let me know if there's anything else. Thank you!

**Comment by the-ethan-hunt** [comment]
Merging this great PR!

**Pull request merged**
