### PR TITLE
Issue #172, Semantic Web

### PR DESCRIPTION
**Pull request by pbiswas101**
#172 NOTE:
- Please fill out the template below 

## Did you read the instructions in the [README](https://github.com/the-ethan-hunt/first-timers-guide/blob/master/README.md)?

> Y

## Have you read the instructions in [CONTRIBUTING](https://github.com/the-ethan-hunt/first-timers-guide/blob/master/CONTRIBUTING.md)?

> Y

## Have you written this article by yourself? Have you taken inspiration from anywhere and then written it in your words?

> I've written this article after taking inspiration from various online resources!

### CODE REVIEW

**Comment by the-ethan-hunt** [comment]
Make the language more lucid for first-timer. There is a lot of technical jargon present in the article.

**Comment by the-ethan-hunt** [comment]
Sorry for the late reply @pbiswas101 ! 
I did not mean by specific terms; what I meant was the overall language. You are free to use these terms as they are used freely.

**Comment by pbiswas101** [comment]
@the-ethan-hunt I have updated the article. Please review it!

**Comment by pbiswas101** [comment]
@the-ethan-hunt @RN0311 please review this!

**Comment by the-ethan-hunt** [comment]
Apologies for not late review! Merging this

**Pull request merged**
