### PR TITLE
Adding information about indexers in C#

### PR DESCRIPTION
**Pull request by Nilkamal**
NOTE:
- Please fill out the template below 

## Did you read the instructions in the [README](https://github.com/the-ethan-hunt/first-timers-guide/blob/master/README.md)?

> Y

## Have you read the instructions in [CONTRIBUTING](https://github.com/the-ethan-hunt/first-timers-guide/blob/master/CONTRIBUTING.md)?

> Y

## Have you written this article by yourself? Have you taken inspiration from anywhere and then written it in your words?

> I have written this article by myself. It is written based on my practical experience with C# language.

### CODE REVIEW

**Comment by the-ethan-hunt** [comment]
Please read the `readme.md` before pulling a PR

**Comment by RN0311** [comment]
@Nilkamal : We appreciate your contribution, can you please have a look at ```README.md``` before submitting a PR!

**Comment by Nilkamal** [comment]
@RN0311 can you please give some direction?

**Comment by RN0311** [comment]
@Nilkamal : Our main motive is to have "simple introductory guides" which doesn't necessarily involves "coding". Please have a look at an excellent PR- https://github.com/the-ethan-hunt/first-timers-guide/pull/66
I hope, this helps!

**Comment by the-ethan-hunt** [comment]
Closing this PR due to stagnation.

**Pull request closed without merging**
