### PR TITLE
added : django.md 

### PR DESCRIPTION
**Pull request by Logan1x**
NOTE:
- Please fill out the template below 

## Did you read the instructions in the [README](https://github.com/the-ethan-hunt/first-timers-guide/blob/master/README.md)?

> Y

## Have you read the instructions in [CONTRIBUTING](https://github.com/the-ethan-hunt/first-timers-guide/blob/master/CONTRIBUTING.md)?

> Y

## Have you written this article by yourself? Have you taken inspiration from anywhere and then written it in your words?

> [inspired from a lot of blogs & articles]

### CODE REVIEW

**Comment by Logan1x** [comment]
for #13 .
CC: @sarahwalter  please review it.

**Comment by RN0311** [comment]
Nice work, @Logan1x!
Reviewed, @the-ethan-hunt.

**Comment by the-ethan-hunt** [comment]
78% plagiarised. A lot of content seems to be coming from the Django girls tutorial(which I used to read)

**Comment by Logan1x** [comment]
@the-ethan-hunt all of content from the thinking is not possible but i will try to edit and push the changes again soon 😄

**Comment by the-ethan-hunt** [comment]
Time window exceeded! Closing this.

**Pull request closed without merging**
